name: Build and Deploy JAR to EC2

on:
  workflow_dispatch:
    inputs:
      trigger_build:
        description: 'Trigger a manual build and deployment'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Copy files via SCP
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}  # Add this secret in GitHub settings
          EC2_USER: ${{ secrets.EC2_USER }}  # Add this secret in GitHub settings
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

        run: |
          mkdir -p ~/.ssh
          echo "$EC2_SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          scp -o StrictHostKeyChecking=no build/libs/io.indisp.backendservice-all.jar $EC2_USER@$EC2_HOST:workspace
