name: Build and Deploy JAR to EC2

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Copy files via SCP
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

        run: |
          mkdir -p ~/.ssh
          echo "$EC2_SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST 'fuser -k 8080/tcp'
          scp -o StrictHostKeyChecking=no build/libs/io.indisp.backendservice-all.jar $EC2_USER@$EC2_HOST:workspace
          ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST 'java -jar ~/workspaceio.indisp.backendservice-all.jar'
